version: "2.1"

services:


  db:
    container_name: cu-mattermost-db
    build:
      context: ./cu-mattermost/db
    image: cu-mattermost-db
    restart: unless-stopped
    volumes:
      - mattermost-dbdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    labels:
      - "traefik.enable=false"

  app:
    container_name: cu-mattermost
    build:
      context: ./cu-mattermost/app
    image: cu-mattermost-app
    restart: unless-stopped
    volumes:
      - mattermost-appconfig:/mattermost/config:rw
      - mattermost-appdata:/mattermost/data:rw
      - mattermost-logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
    labels:
      - "traefik.frontend.entryPoints=https"
      - "traefik.backend=cu-mattermost"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${CU_MATTERMOST_DOMAIN}"
    depends_on:
      - db

networks:
  default:
    external:
      name: skynet

volumes:
  mattermost-logs:
  mattermost-appdata:
  mattermost-appconfig:
  mattermost-dbdata:
