version: '2.1'
services:

  testmysql:
      container_name: cuplatform_testmysql_1
      image: mysql:5.7.4
      depends_on:
           - mysqldata
      ports:
           - "3307:3306"
      environment:
          - MYSQL_ROOT_PASSWORD
          - MYSQL_DATABASE=cloudunit
          - "http_proxy=${http_proxy}"
          - "https_proxy=${https_proxy}"
          - "ftp_proxy=${ftp_proxy}"
          - "no_proxy=${no_proxy}"
      volumes_from:
           - testmysqldata
      volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
      network_mode: bridge

  testmysqldata:
      container_name: cuplatform_testmysqldata_1
      image: ubuntu:14.04
      volumes:
          - /home/vagrant/testmysql_home:/var/lib/mysql
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      network_mode: bridge
