version: '2.1'
services:

  redis:
      container_name: cu-redis
      image: redis:3.0.1
      command: redis-server --appendonly yes
      environment:
          - "TZ=${TZ}"
          - "http_proxy=${http_proxy}"
          - "https_proxy=${https_proxy}"
          - "ftp_proxy=${ftp_proxy}"
          - "no_proxy=${no_proxy}"
      volumes:
          - redis-data:/data
      labels:
          - "traefik.enable=false"

  mysql:
      container_name: cu-mysql
      image: mysql:5.7.4
      environment:
          - "TZ=${TZ}"
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - "http_proxy=${http_proxy}"
          - "https_proxy=${https_proxy}"
          - "ftp_proxy=${ftp_proxy}"
          - "no_proxy=${no_proxy}"
      volumes:
            - mysqldata:/var/lib/mysql
      labels:
            - "traefik.enable=false"

  tomcat:
      container_name: cu-tomcat
      image: cloudunit/manager
      ports:
          - "8080:8080"
      environment:
          - "TZ=${TZ}"
          - CATALINA_OPTS="-Dspring.profiles.active=vagrant-demo"
          - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
          - "CU_JENKINS_DOMAIN=${CU_JENKINS_DOMAIN}"
          - "CU_DOMAIN=${CU_DOMAIN}"
          - "CU_GITLAB_DOMAIN=${CU_GITLAB_DOMAIN}"
          - "CU_KIBANA_DOMAIN=${CU_KIBANA_DOMAIN}"
          - "CU_NEXUS_DOMAIN=${CU_NEXUS_DOMAIN}"
          - "CU_SONAR_DOMAIN=${CU_SONAR_DOMAIN}"
          - "CU_MATTERMOST_DOMAIN=${CU_MATTERMOST_DOMAIN}"
          - "http_proxy=${http_proxy}"
          - "https_proxy=${https_proxy}"
          - "ftp_proxy=${ftp_proxy}"
          - "no_proxy=${no_proxy}"
      labels:
          - "traefik.frontend.entryPoints=https"
          - "traefik.backend=manager"
          - "traefik.port=8080"
          - "traefik.frontend.rule=Host:${CU_MANAGER_DOMAIN}"

  cadvisor:
      container_name: cu-advisor
      image: google/cadvisor:0.14.0
      environment:
          - "TZ=${TZ}"
          - DB_USER=root
          - DB_PASS=root
          - DB_NAME=cadvisor
          - "http_proxy=${http_proxy}"
          - "https_proxy=${https_proxy}"
          - "ftp_proxy=${ftp_proxy}"
          - "no_proxy=${no_proxy}"
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker:/var/lib/docker:ro
      command: --housekeeping_interval=5s
      labels:
          - "traefik.enable=false"

  gitlab:
      container_name: cu-gitlab
      image: gitlab/gitlab-ce:8.14.5-ce.0
      volumes:
          - gitlab-config:/etc/gitlab
          - gitlab-logs:/var/log/gitlab
          - gitlab-data:/var/opt/gitlab
          - ./cu-gitlab-ce/gitlab.rb:/etc/gitlab/gitlab.rb
      hostname: '${CU_GITLAB_DOMAIN}'
      ports:
          - "1212:22"
      environment:
          - "TZ=${TZ}"
          - "http_proxy=${http_proxy}"
          - "https_proxy=${https_proxy}"
          - "ftp_proxy=${ftp_proxy}"
          - "no_proxy=${no_proxy}"
      environment:
        GITLAB_OMNIBUS_CONFIG: |
               external_url 'https://${CU_GITLAB_DOMAIN}'
      labels:
          - "traefik.frontend.entryPoints=https"
          - "traefik.backend=gitlab"
          - "traefik.port=443"
          - "traefik.frontend.rule=Host:${CU_GITLAB_DOMAIN}"

  jenkins:
      container_name: cu-jenkins
      build:
        context: cu-jenkins
      image: cloudunit/jenkins
      volumes:
          - jenkins-home:/var/jenkins_home
      environment:
          - "TZ=${TZ}"
          - "http_proxy=${http_proxy}"
          - "https_proxy=${https_proxy}"
          - "ftp_proxy=${ftp_proxy}"
          - "no_proxy=${no_proxy}"
      labels:
          - "traefik.frontend.entryPoints=https"
          - "traefik.backend=jenkins"
          - "traefik.port=8080"
          - "traefik.frontend.rule=Host:${CU_JENKINS_DOMAIN}"

  traefik:
      container_name: cu-traefik
      image: traefik
      command: --web --docker --docker.domain=${CU_DOMAIN} --logLevel=DEBUG --docker.exposedbydefault=true --docker.watch=true
      environment:
          - "TZ=${TZ}"
      ports:
          - "80:80"
          - "443:443"
          - "9090:8080"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./cu-traefik/traefik.toml:/traefik.toml
          - ./cu-traefik/certs:/certs
      labels:
        - "traefik.enable=false"

networks:
  default:
    external:
      name: skynet

volumes:
  mysqldata:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins-home:
  traefik-certs:
  redis-data:
