version: '2.1'
services:

  redis:
      container_name: cu-redis
      image: redis:3.0.1
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - redis-data:/data
      labels:
        - "traefik.enable=false"
      environment:
        - "http_proxy=${http_proxy}"
        - "https_proxy=${https_proxy}"
        - "ftp_proxy=${ftp_proxy}"
        - "no_proxy=${no_proxy}"

  mysql:
      container_name: cu-mysql
      env_file: .env
      image: mysql:5.7.4
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - "http_proxy=${http_proxy}"
        - "https_proxy=${https_proxy}"
        - "ftp_proxy=${ftp_proxy}"
        - "no_proxy=${no_proxy}"
      volumes:
        - mysqldata:/var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      labels:
        - "traefik.enable=false"

  cadvisor:
      container_name: cuplatform_cadvisor_1
      image: google/cadvisor:0.14.0
      environment:
        - DB_USER=root
        - DB_PASS=root
        - DB_NAME=cadvisor
        - "http_proxy=${http_proxy}"
        - "https_proxy=${https_proxy}"
        - "ftp_proxy=${ftp_proxy}"
        - "no_proxy=${no_proxy}"
      ports:
        - "8081:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker:/var/lib/docker:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      command: --housekeeping_interval=5s
      labels:
        - "traefik.enable=false"

  gitlab:
      env_file: .env
      container_name: cu-gitlab
      image: gitlab/gitlab-ce:8.14.5-ce.0
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - gitlab-config:/etc/gitlab
        - gitlab-logs:/var/log/gitlab
        - gitlab-data:/var/opt/gitlab
        - ./cu-gitlab-ce/gitlab.rb:/etc/gitlab/gitlab.rb
      # Define the CU_GITLAB_DOMAIN into /etc/environment
      hostname: '${CU_GITLAB_DOMAIN}'
      environment:
          GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://${CU_GITLAB_DOMAIN}'
        - "http_proxy=${http_proxy}"
        - "https_proxy=${https_proxy}"
        - "ftp_proxy=${ftp_proxy}"
        - "no_proxy=${no_proxy}"
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.backend=cu-gitlab"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:gitlab.${CU_DOMAIN}"

  jenkins:
      container_name: cu-jenkins
      user: root
      build:
        context: cu-jenkins
      image: cloudunit/jenkins
      environment:
        - "JAVA_OPTS=-Xmx512m"
        - "http_proxy=${http_proxy}"
        - "https_proxy=${https_proxy}"
        - "ftp_proxy=${ftp_proxy}"
        - "no_proxy=${no_proxy}"
      volumes:
        - jenkins-home:/var/jenkins_home
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.backend=cu-jenkins"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:jenkins.${CU_DOMAIN}"

  nexus:
      container_name: cu-nexus
      image: sonatype/nexus3:3.2.0
      ports:
        - "9091:8081"
        - "8123:8123"
      volumes:
        - "nexus-data:/nexus-data"
      environment:
        - "JAVA_MIN_MEM=512m"
        - "JAVA_MAX_MEM=512m"
        - "http_proxy=${http_proxy}"
        - "https_proxy=${https_proxy}"
        - "ftp_proxy=${ftp_proxy}"
        - "no_proxy=${no_proxy}"
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.backend=cu-nexus"
        - "traefik.port=8081"
        - "traefik.frontend.rule=Host:nexus.${CU_DOMAIN}"

  sonarqube:
    container_name: cu-sonar
    image: 'sonarqube:6.2'
    volumes:
      - 'sonar-data:/opt/sonarqube/data'
      - 'sonar-extensions:/opt/sonarqube/extensions'
    labels:
      - "traefik.frontend.entryPoints=http"
      - "traefik.backend=cu-sonar"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:sonar.${CU_DOMAIN}"
    environment:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
      - "ftp_proxy=${ftp_proxy}"
      - "no_proxy=${no_proxy}"

  traefik:
      container_name: cu-traefik
      env_file: .env
      image: traefik:1.2.0
      command: --web --docker --docker.domain=${CU_DOMAIN} --logLevel=DEBUG --docker.exposedbydefault=true --docker.watch=true
      ports:
        - "80:80"
        - "443:443"
        - "9090:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./cu-traefik/traefik.toml:/traefik.toml
        - ./cu-traefik/certs:/certs
      labels:
        - "traefik.enable=false"

networks:
  default:
    external:
      name: skynet

volumes:
  mysqldata:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins-home:
  sonar-data:
  sonar-extensions:
  traefik-certs:
  redis-data:
  nexus-data:
