version: '2.1'
services:

  elasticsearch:
    container_name: cu-elasticsearch
    build:
      context: ./cu-elk/elasticsearch
    image: cloudunit/elk-elasticsearch
    #ports:
    #  - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - "TZ=${TZ}"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    privileged: true
    command: -E cluster.name="cu-mon" -E node.master=true -E node.data=true
    labels:
       - "traefik.enable=false"

  kibana:
    container_name: cu-kibana
    build:
      context: ./cu-elk/kibana
    image: cloudunit/elk-kibana
    ports:
      - "5601:5601"
    volumes:
      - ./cu-elk/kibana/file:/opt/cloudunit/file
    environment:
      - "TZ=${TZ}"
      - "ELASTICSEARCH_URL=http://$ELASTICSEARCH_URL:9200"
    depends_on:
      - elasticsearch
    labels:
      - "traefik.frontend.entryPoints=https"
      - "traefik.backend=kibana"
      - "traefik.port=5601"
      - "traefik.frontend.rule=Host:${CU_KIBANA_DOMAIN}"

  monitoring-agents:
    container_name: cu-monitoring-agents
    hostname: ${HOSTNAME}
    build:
      context: cu-elk/monitoring-agents
    image: cloudunit/elk-monitoring-agents
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cu-elk/monitoring-agents/metricbeat-conf:/opt/cloudunit/monitoring-agents/metricbeat/conf.d
      - monitoring-agents:/opt/cloudunit/monitoring-agents
    environment:
      - "TZ=${TZ}"
      - "ELASTICSEARCH_URL=$ELASTICSEARCH_URL"
      - "HOSTNAME=${HOSTNAME}"
    labels:
      - "traefik.enable=false"
    depends_on:
      - elasticsearch

networks:
  default:
    external:
      name: skynet

volumes:
  elasticsearch-data:
  monitoring-agents:
